### ISSUE TITLE
Post sobre buenas prácticas para crear Dockerfiles

### ISSUE THREAD

**Issue by itelleria** [wearearima/blog#14]

**Comment by UrkoLekuona** [comment]
Entiendo que quieres un post similar al del repo cloud-research, ¿no? ¿Qué cambiarías de ese documento?

**Comment by jagobagascon** [comment]
Antes de que cerréis la issue: algunos párrafos no se ven bien en móviles porque tienen código `inline` muy largo y no cabe en una sola línea. Podéis verlo en el punto 5.

Igual lo suyo es utilizar bloques de código que tienen scroll.

Aquí: https://github.com/wearearima/wearearima.github.io/blame/master/_posts/2020-04-21-buenas-practicas-para-escribir-un-dockerfile.markdown#L85

**Comment by UrkoLekuona** [comment]
> Antes de que cerréis la issue: algunos párrafos no se ven bien en móviles porque tienen código `inline` muy largo y no cabe en una sola línea. Podéis verlo en el punto 5.
> 
> Igual lo suyo es utilizar bloques de código que tienen scroll.
> 
> Aquí: https://github.com/wearearima/wearearima.github.io/blame/master/_posts/2020-04-21-buenas-practicas-para-escribir-un-dockerfile.markdown#L85

Tienes razón, es algo en lo que no me había fijado.

Ahora lo soluciono y lo tendré en cuenta para futuros posts. Como el PR ya se ha mergeado, haré uno nuevo.

Gracias!
