### ISSUE TITLE
Uso de Jekyll Polyglot en el blog

### ISSUE THREAD

**Issue by UrkoLekuona** [wearearima/blog#26]
Si acabamos utilizando Jekyll Polyglot para dar soporte multilenguaje a nuestro blog (ver [issue de Gitlab](https://gitlab.com/arimadev/cloud-research/-/issues/44)(privada)), habrá que tomar ciertas decisiones tanto para la apariencia del blog como para la estructura interna:

# Apariencia

## URL

Aquí veo dos problemas a decidir:

### 1. 
Para que Polyglot asocie las diferentes versiones del mismo post, utiliza los permalinks de cada post.
  > Polyglot works by associating documents with similar permalinks to the lang specified in their frontmatter. Files that correspond to similar routes should have identical permalinks. - _Extraído del [repositorio de Polyglot](https://github.com/untra/polyglot)_

Como nuestro permalink es `permalink: /:year/:month/:day/:title:output_ext`, esto implica que los nombres de archivos para ambas versiones deben de ser iguales (`:title` corresponde al nombre del archivo, no al título del frontmatter). El resultado es que las URLs de las versiones están en el mismo idioma. Ejemplo:

* URL de un post en castellano:
`http://localhost:4000/2020/04/21/buenas-practicas-para-escribir-un-dockerfile.html`
* URL del mismo post en inglés:
`http://localhost:4000/en/2020/04/21/buenas-practicas-para-escribir-un-dockerfile.html`

¿Es esto un problema? Si cambio el nombre del archivo en inglés a "2020-04-21-dockerfile-best-practices.markdown", la URL en inglés cambia a `http://localhost:4000/en/2020/04/21/dockerfile-best-practices.html`, pero ya no lo asocia con su versión en castellano, así que no sirve.

### 2.
¿Cómo queremos que sea la URL de la versión en castellano? Actualmente, la versión en ingles es `http://localhost:4000/en`, y hay que decidir si queremos que en castellano sea:
* `http://localhost:4000`
o
* `http://localhost:4000/es`

## Selección de idioma

Si hacemos un blog multilenguaje, habrá que añadir un selector del idioma actual en algún sitio (cambiarlo por URL no es lo ideal). Se me ocurre que podemos añadir uno en el header/footer del blog y en cada post un enlace a la versión alternativa. ¿Qué opináis?

# Estructura

## Organización de los posts

Esto esta relacionado con el problema de la URL. Utilizando el permalink actual, la manera en la que habría que organizar los posts para que el plugin funcione correctamente es crear un directorio dentro de `_posts` llamado `en` que contendrá todos los posts en inglés. ¿Qué vamos a hacer con la versión en castellano? ¿Los dejamos en `_posts` o movemos a `_posts/es`? Es decir:
Esto:
 ```
_posts
|
|- en
|   |
|   |- postIngles.md
|
|- postCastellano.md
```
o esto:
```
_posts
|
|- en
|   |
|   |- postIngles.md
|
|- es
    |
    |- postCastellano.md
```

## Versiones de recursos

No lo he probado aún, pero entiendo que los posts que contengan recursos con contenido en castellano, también necesitarán que esos recursos sean traducido. ¿Vamos a estructurar la carpeta `assets` de alguna manera?

**Comment by aberasarte** [comment]
Doy mi opinión sobre los puntos que comentas:

## URL
### 1
Si he entendido bien el problema, ¿puede que lo que comentan [en esta issue](https://github.com/untra/polyglot/issues/98) sea lo que necesitamos?

### 2
Si es posible, yo me inclinaría por hacer que la URL fuera `http://localhost:4000/es` pero que como fallback la URL `http://localhost:4000` también llevase a la versión en castellano. 

No sé si esto es posible. Si no lo es, dejaría que directamente `http://localhost:4000` fuese la versión en castellano.

### Selección de idioma
> Si hacemos un blog multilenguaje, habrá que añadir un selector del idioma actual en algún sitio (cambiarlo por URL no es lo ideal). Se me ocurre que podemos añadir uno en el header/footer del blog y en cada post un enlace a la versión alternativa. ¿Qué opináis?

Añadir un selector de idioma en la cabecera me parece perfecto.

## Estructura
### Organización de los post
Voto por esta opción:
```
_posts
|
|- en
|   |
|   |- postIngles.md
|
|- es
    |
    |- postCastellano.md
```

## Versiones de recursos
Para las imágenes en las que metemos texto tendremos que tener dos versiones: una con los textos en inglés y otra en castellano. No sé si sería posible hacer algo parecido a esto: 

```
assets
|
|- images
|   |-2020-02-11-java-en-contenedores-docker
|   |   |- servidor-java-ee-en.png
|   |   |- servidor-java-ee-es.png
|   |   |- no-body-puts-java-in-a-container.png
```
Es decir, para aquellas imágenes que están internacionalizadas añadimos un sufijo con el locale y para las que no lo están, las dejamos tal cual. 

La verdad es que por no complicar, no me parecería mal que las imágenes siempre tuvieran los textos en inglés.

**Comment by UrkoLekuona** [comment]
# Apariencia

## URL

### 1

Sí, lo que comentan en la issue es exactamente lo que queremos. Pero la issue sigue abierta, el autor del plugin no ha comentado nada (aunque lo ha visto, por un emoticono en uno de los comentarios) y las soluciones que dan no me gustan. Lo ideal sería darle a cada post una referencia (como hace la persona que abre el issue y en este [post](https://forestry.io/blog/creating-a-multilingual-blog-with-jekyll/)).

También he visto que los creadores de [https://streetrunners.net/](https://streetrunners.net/) sí que lo han conseguido de alguna manera, pero no he visto un enlace a su repositorio (sí a [su cuenta](https://github.com/streetrunners)). Estoy por mandarles un correo y pedir que me dejen echar un vistazo a ver qué opinan.

### 2

Hecho, la versión en inglés está en `/en/`y la versión en castellano en `/es/` y `/`.

## Selección de idioma

Me pongo a ello

# Estructura

## Organización de los post

Hecho.

## Versiones de recursos

Se puede sin problema, pero hay que gestionar los enlaces de manera manual. Es decir, a la hora de traducir el post a inglés habrá que modificar los enlaces a los recursos que hayan cambiado. De esto no se encarga el plugin (o no he visto nada que lo indique y las pruebas que he hecho no me han funcionado).

¿Es esto un problema?

**Comment by UrkoLekuona** [comment]
## Selección de idioma
¿Opiniones?

![Screenshot 2020-05-06 at 11 30 48](https://user-images.githubusercontent.com/17404249/81162221-1e50e480-8f8d-11ea-92e7-feac226a7cc7.png)

**Comment by jagobagascon** [comment]
Yo lo haría más sutil, o incluso lo movería al footer.

**Comment by uurien** [comment]
¿Qué tal algo así?
<img width="1680" alt="Captura de pantalla 2020-05-06 a las 11 38 22" src="https://user-images.githubusercontent.com/1437996/81163393-f6fb1700-8f8e-11ea-80ce-21dc80cc2433.png">
<img width="391" alt="Captura de pantalla 2020-05-06 a las 11 41 06" src="https://user-images.githubusercontent.com/1437996/81163405-fcf0f800-8f8e-11ea-8ad5-da33e530139f.png">
En negrita estaría el actual.
@jagobagascon En el footer tampoco lo pondría, si el post es largo estaría demasiado abajo para verlo.

**Comment by aberasarte** [comment]
> Sí, lo que comentan en la issue es exactamente lo que queremos. Pero la issue sigue abierta, el autor del plugin no ha comentado nada (aunque lo ha visto, por un emoticono en uno de los comentarios) y las soluciones que dan no me gustan. Lo ideal sería darle a cada post una referencia (como hace la persona que abre el issue y en este [post](https://forestry.io/blog/creating-a-multilingual-blog-with-jekyll/)).

Ah pues sin haber entrado en detalles, a mí sí que me encajaba lo de utilizar un front-matter de este estilo para definir los permalinks internacionalizados:

```
permalink_i18n:
    es: "/permalink_en_español/"
    en: "/permalink_in_english/"
```

Supongo que lo han copiado de [este otro plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin#53-permalinks-and-translating-links) que creo que también habíamos valorado y descartado en favor de Polyglot. No sé si el hecho de que tengan contemplado esto puede hacer que volvamos a valorarlo.

**Comment by UrkoLekuona** [comment]
![Screenshot 2020-05-06 at 12 29 44](https://user-images.githubusercontent.com/17404249/81167355-5d833380-8f95-11ea-93b6-18539cb2d9b8.png)

Aún falta el selector del toolbar. ¿Opiniones? A mí personalmente me parece un poco pequeño.

**Comment by UrkoLekuona** [comment]
### Selector en el toolbar para desktop:
![Screenshot 2020-05-06 at 12 35 58](https://user-images.githubusercontent.com/17404249/81168576-89071d80-8f97-11ea-946c-f8aeaa62d751.png)

### Selector en el toolbar para móviles:
![Screenshot 2020-05-06 at 12 45 21](https://user-images.githubusercontent.com/17404249/81168568-860c2d00-8f97-11ea-8b9c-e6e0777f193a.png)

**Comment by uurien** [comment]
Así como en la home si que me gusta que esté del todo en la esquina, en la toolbar, al tener ARIMA a la izquierda, pero no del todo a la izquierda, me canta un poco que el cambio de idioma se vaya hasta la esquina, en la toolbar lo dejaría alineado con el texto, _(en la esquina de la capa wrapper)_.
En la toolbar, centraría el texto verticalmente y lo haría un poco más pequeño.

**Comment by UrkoLekuona** [comment]
>En la toolbar, centraría el texto verticalmente y lo haría un poco más pequeño.

Entiendo que te refieres a la versión móvil.

>Así como en la home si que me gusta que esté del todo en la esquina, en la toolbar, al tener ARIMA a la izquierda, pero no del todo a la izquierda, me canta un poco que el cambio de idioma se vaya hasta la esquina, en la toolbar lo dejaría alineado con el texto, (en la esquina de la capa wrapper

Y con esto solo a la versión escritorio, ¿no?

**Comment by uurien** [comment]
> Entiendo que te refieres a la versión móvil

No, me refiero a ambos, pero en la toolbar (o navbar). ES | EN no está centrado verticalmente en ninguno de los dos. Y lo pondría un poco más pequeño en ambos.
> Y con esto solo a la versión escritorio, ¿no?

Realmente la toolbar es la misma en mobile y escritorio, pero si, con este comentario me refería a la versión de escritorio.

**Comment by UrkoLekuona** [comment]
![Screenshot 2020-05-06 at 13 29 28](https://user-images.githubusercontent.com/17404249/81171995-b35bd980-8f9d-11ea-9f56-024c84bc2995.png)
![Screenshot 2020-05-06 at 13 29 48](https://user-images.githubusercontent.com/17404249/81172002-b5be3380-8f9d-11ea-9d1f-da8e7a337a9d.png)

Alinearlo verticalmente me ha costado más de lo que debería y ni siquiera sé si lo está del todo...

**Comment by UrkoLekuona** [comment]
>Supongo que lo han copiado de este otro plugin que creo que también habíamos valorado y descartado en favor de Polyglot. No sé si el hecho de que tengan contemplado esto puede hacer que volvamos a valorarlo.

@aberasarte ¿Qué te parece si intentamos integrar Polyglot (con la pega de solo poder utilizar un frontmatter para ambas versiones) y si acabamos mergeando abrimos otra issue intentando añadir multiple frontmatters / otro plugin?

Lo digo porque ahora que este está ya a punto de hacer el pull request y ahora dar marcha atrás en la mitad de cosas solo para ver qué otros problemas surgen al utilizar otro plugin... me voy a volver loco y la issue no va a haber quien la siga.

**Comment by aberasarte** [comment]
> >Supongo que lo han copiado de este otro plugin que creo que también habíamos valorado y descartado en favor de Polyglot. No sé si el hecho de que tengan contemplado esto puede hacer que volvamos a valorarlo.
> 
> 
> 
> @aberasarte ¿Qué te parece si intentamos integrar Polyglot (con la pega de solo poder utilizar un frontmatter para ambas versiones) y si acabamos mergeando abrimos otra issue intentando añadir multiple frontmatters / otro plugin?
> 
> 
> 
> Lo digo porque ahora que este está ya a punto de hacer el pull request y ahora dar marcha atrás en la mitad de cosas solo para ver qué otros problemas surgen al utilizar otro plugin... me voy a volver loco y la issue no va a haber quien la siga.

Me parece bien.
