### ISSUE TITLE
En el index del home no se ven todos los posts en castellano

### ISSUE THREAD

**Issue by jaguado-arima** [wearearima/blog#87]
@UrkoLekuona @itelleria @aberasarte

Al introducir el euskera y poner en cada "index" sólo los posts de ese idioma ha quedado al descubierto un problemilla: y es que no se ven todos los posts de cada idioma, sólo aquellos que NO están traducidos al euskera.

Hemos encontrado cuál es el problema: para cargar la variable site.posts se hace recorriendo todas las carpetas en orden alfabético. El orden de las carpetas es: en, es, eus. Qué sucede? Que por cada post se está quedando el último que encuentra. Así en el caso de los que están en euskera siempre se queda con la versión en euskera. Eso sólo sucede para el caso de la raiz, ya que tenemos puesto el idioma por defecto "_".

Si cambiamos el idioma por defecto a "es" funciona, PERO nos quedamos sin la ruta /es/.

Hemos valorado la opción de prescindir de esta ruta PERO hay tuits que hacen referencia a ella, así que la hemos descartado.

Después de mucho mirar, probar, hacer cambios etc. sólo se nos ocurren 2 workarounds, que son un poco meg.

1.- Poner el idioma por defecto a "es" y en el github actions añadir un paso que sea, crear una carpeta "es" y copiar todo lo que hay en la raiz en esa carpeta.

2.- Renombrar las carpetas dentro de _posts para que el último idioma por el que pase sea el de defecto.

Hemos optado por esta última. De tal forma que poniendo lang_def_es conseguimos que todo funcione ok. Como digo, tenemos claro que es una trampa, pero nos parece la trampa menos "cochina", ya que si en algún momento queremos cambiar el idioma por defecto, únicamente tendríamos que renombrar esta carpeta a "es" y poner a la que queramos que sea la de defecto lang_def_xx

**Comment by aberasarte** [comment]
Solucionado en #88 así que cierro.
